

export const skillsData = [
    { href: "#git_", title: "Git" },
    { href: "#json_", title: "JSON" },
    { href: "#railway_", title: "Railway" },
    { href: "#html_", title: "HTML" },
    { href: "#react_", title: "React" },
    { href: "#rest_", title: "REST" },
    { href: "#sql_", title: "SQL" },
    { href: "#mongo_", title: "MongoDB" },
    { href: "#aws_", title: "AWS" },
    { href: "#bootstrap", title: "Bootstrap" },
    { href: "#npm_", title: "npm" },
    { href: "#css_", title: "CSS" },
    { href: "#jquery_", title: "jQuery" },
    { href: "#js_", title: "JavaScript" },
    { href: "#express", title: "Express.js" },
    { href: "#passport_js", title: "Passport.js" },
    { href: "#redux", title: "Redux" },
    { href: "#mongoose", title: "Mongoose" },
    { href: "#nux", title: "NUX" },
    { href: "#postman", title: "Postman" },
    { href: "#idee", title: "IDEE" },
    { href: "#node.js_", title: "Node.js" },
    { href: "#webstorm", title: "Webstorm" },
    { href: "#google", title: "Google Cloud" },
    { href: "#figma", title: "Figma" },
    { href: "#illustrator_", title: "Illustrator" },
    { href: "#vs", title: "Visual Studio Code" },
    { href: "#threejs", title: "Three.js" },
    { href: "#stripe", title: "Stripe" },
    { href: "#canvas", title: "Canvas" },
   ]